"""message

Revision ID: 858337850e31
Revises: 3363607badd1
Create Date: 2024-07-08 05:36:36.401017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '858337850e31'
down_revision = '3363607badd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
